variable "ami" {}
variable "instance_type" {}
variable "security-group" {}
variable "key_name" {}
variable "subnet_id" {}
variable "private_keypair_path" {}
variable "tags" {}
variable "stage-playbook" {}
variable "prod-playbook" {}
variable "stage-bash-script" {}
variable "prod-bash-script" {}
variable "stage-trigger" {}
variable "prod-trigger" {}
variable "password" {}
variable "private-key" {}
variable "nexus-ip" {}